### ISSUE TITLE
Error running Perfume.js: TypeError: Failed to execute 'observe' on 'PerformanceObserver'

### ISSUE THREAD

**Issue by dangxquang** [Zizzamia/perfume.js#102]
I run the sample with React but no luck. Perfume only track navigation timing and show some error with entryType
![image](https://user-images.githubusercontent.com/49668846/71661216-1b947780-2d80-11ea-9139-0f533246f83a.png)

**Comment by Zizzamia** [comment]
Ciao @dangxquang and thank you for opening this issue.
Would you mind sharing some extra information like:
- Perfume version
- How did you install Perfume
- The code on how you are using Perfume

Thank you

**Comment by dangxquang** [comment]
https://codesandbox.io/s/perfume-react-u1y2f
@Zizzamia I have a demo on Code sandbox. Just use create-react-app template with the react example. 
My browser is Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by dangxquang** [comment]
I also have a question about TTI. My page is a dashboard with the products list. Currently, I have to call many APIs to aggregate the data needed to complete render in react. So in my use case, I think TTI is an important metric to keep track of. I haven't found any solution to use `tti-pollify` because it won't have the right TTI when navigating between routes. Do you have any suggestion @Zizzamia?

**Comment by Zizzamia** [comment]
@dangxquang interesting, in https://codesandbox.io/s/perfume-react-u1y2f with Chrome 79 I don't see the error. It might be a problem with Chrome 73.

Would you mind help me debug this error by turning on and off those configs:
```js
firstContentfulPaint: true,
  firstInputDelay: true,
  dataConsumption: true,
  navigationTiming: true,
  resourceTiming: true,
```

and see what of those introduces the error. I have a feeling it might be one of the latest PerformanceObserver APIs.

**Comment by Zizzamia** [comment]
In the past, I express already why I removed TTI from Perfume https://github.com/Zizzamia/perfume.js/issues/54#issuecomment-437533867

The tldr is that a better metric you should use is LCP mixed with the Network Information. Monitoring the largest contentful paint when users are in 3g is a more stable metric to understand when the page become useful for your users.

Let me know if you have more questions or curiosity, happy to help. 😁

**Comment by dangxquang** [comment]
> @dangxquang interesting, in https://codesandbox.io/s/perfume-react-u1y2f with Chrome 79 I don't see the error. It might be a problem with Chrome 73.
> 
> Would you mind help me debug this error by turning on and off those configs:
> ...
> and see what of those introduces the error. I have a feeling it might be one of the latest PerformanceObserver APIs.

Yeah, it is a problem with Chrome 73. I successfully update to Chrome 79 and everything running fine.
One question though, I track firstContentfulPaint + largestContentfulPaint but I only see log from firstContentfulPaint. largestContentfulPaint is sometime miss or hit, or just not logging at all.

**Comment by Zizzamia** [comment]
In Perfume the developer is notified with the latest LCP duration when First Input Delay is fired, because Largest Contentful Paint is deactivated after user input. If main content shows up after any user input, then the largest element that LCP uses won’t reflect the main content.

One challenge with exposing LCP only after FID is the fact that the browser is not aware of the "winning" candidate until the measurement is over, at which point it is potentially too late, as the user may have navigated away.

But, we find that using aggregate statistics for higher percentiles, such as 90th, avoids bias due to these early aborts.

**Comment by dangxquang** [comment]
Thank you for the clarification.
One last question though, FCP and FID only true when the page is first-time load right? In SPA, when I need to measure components render time, I need to use a custom metric or just re-init perfume?

**Comment by Zizzamia** [comment]
@dangxquang for the original question, do you still have problem for Chrome 73?

**Comment by asvae** [comment]
Just tested perfume on chrome 73, and had no issues. So probably closable.

**Comment by Zizzamia** [comment]
Thank you @asvae
