### ISSUE TITLE
Listed options in docs are not actually used.

### ISSUE THREAD

**Issue by tylercrocker** [Zizzamia/perfume.js#105]
```
firstContentfulPaint: false,
firstPaint: false,
firstInputDelay: false,
largestContentfulPaint: false
```

None of these options that are listed in the docs actually do anything. I would actually really like to be able to disable these for a custom set of timings I'm doing and I don't need those to be triggered over and over... Also, "warn" is not a config option at all, but is listed in your docs.

**Comment by Zizzamia** [comment]
Yup, good call. I forgot to update the doc after a few changes I made a few weeks ago. Thank you I will make sure to update the doc this weekend.

From now on FP, FCP, FID, and LCP will be always triggered once per session because are highly important as field data https://youtu.be/iaWLXf1FgI0?t=451.

**Comment by Zizzamia** [comment]
Did some clean up on the README and added a new [QuickStart](https://github.com/Zizzamia/perfume.js#quick-start) section. Now I just need to fix the official doc and deploy them 😆

**Comment by tylercrocker** [comment]
Awesome, thanks for updating the docs!

I'm assuming by "once per session" you mean "once per perfume instance". We were trying to write up a thing where we had a separate Perfume.js instance running and it then causes all of those default timing data to call all over again. Any thoughts?

**Comment by Zizzamia** [comment]
Right right, Perfume should have **only one** instance per each session. It's better to have it as a singleton and share the instance cross pages and components.

**Comment by tylercrocker** [comment]
OK cool, thanks for the confirmation on that! I'd suggest maybe adding a section to the readme warning about that?

**Comment by Zizzamia** [comment]
Did some nice update on the doc https://zizzamia.github.io/perfume, for the last question feel free to open up a new issue and if you want open a PR.

I am going to close this issue because the original answer got resolved. Thank you
