### ISSUE TITLE
What about browser compatibility？

### ISSUE THREAD

**Issue by warpcgd** [Zizzamia/perfume.js#106]
Hello guys, I want to know browser compatibility？Minimum supported Chrome version？

**Comment by Zizzamia** [comment]
Perfume uses a large collection of APIs, which tends to have different browser compatibility. The goal for Perfume is to fully support all the latest APIs and simply silently not return results for the old browser.

Here a quick list:
**Network Information API - effectiveType**: Chrome 61+, Opera 48+, Edge 76+, Chrome for Android 76+, Firefox for Android 68+
**Save Data API**: Chrome 65+, Opera 62+, Chrome for Android 76+, Opera for Android 46+
**Hardware Concurrency API**: Chrome 37+, Safari 10.1+, Firefox 48+, Opera 24+, Edge 15+, Chrome for Android 76+, Safari on iOS 10.3+, Firefox for Android 68+, Opera for Android 46+
**Performance memory API**: Chrome 7+, Opera, Chrome for Android 18+, Opera for Android
**Device Memory API**: Chrome 63+, Opera 50+, Chrome for Android 76+, Opera for Android 46+

I missed probably some particular method, like Performance Observer, but yeah feel free to ask any API or method, in particular, you are curious about.

**Comment by warpcgd** [comment]
Thanks
