### ISSUE TITLE
Integration with Prometheus/Grafana

### ISSUE THREAD

**Issue by ngrkishore** [Zizzamia/perfume.js#107]
Hi,
Is it possible to use Prometheus rather than google analytics to expose the metrics?

**Comment by Zizzamia** [comment]
You can use any analytics you prefer, Perfume.js does not pick anything for you at the moment.
Follow the [Quick start](https://github.com/Zizzamia/perfume.js#quick-start) and replace `myAnalyticsTool` with the one you prefer most.
