### ISSUE TITLE
List All Features

### ISSUE THREAD

**Issue by DanielSokil** [Zizzamia/perfume.js#11]
What does this library do at this point?

**Comment by Zizzamia** [comment]
Ciao, here the documentation about `perfume.start()` and `perfume.end()`.
https://github.com/Zizzamia/perfume.js/tree/v0.2.2#start-measuring

Next methods coming up are: `perfume.endPaint`, `perfume.endPaint`.
And the option to enable Google Analytics.

**Comment by DanielSokil** [comment]
@Zizzamia Could you provide a compiled js script? From what I see you only have a ts script.

**Comment by Zizzamia** [comment]
Have you tried installing the library by using [npm](https://www.npmjs.com/package/perfume.js)?

    npm install perfume.js --save

The location of the latest UMD version it's here
https://unpkg.com/perfume.js@0.2.6/dist/perfume.umd.js

**Comment by Zizzamia** [comment]
Here all the features: http://zizzamia.github.io/perfume/
