### ISSUE TITLE
Resource Timing in Firefox

### ISSUE THREAD

**Issue by nickcox** [Zizzamia/perfume.js#111]
First off: thanks for your efforts, I love this library.

I have an issue capturing resource timings in Firefox (75.0) with the following config:

```js
new Perfume({ resourceTiming: true, logging: true })
```

I'm able to see resource timings logged in Chrome but not Firefox. (Firefox does log navigation timings though.) Is this something that's expected to work?

**Comment by Zizzamia** [comment]
Thank you 💛
Would you mind sharing a screenshot of what you are seeing between Chrome and Firefox?
And exactly what version of the two you are using.

Firefox is a little behind on supporting several Web Performance API, and Perfume.js instead of mocking the value, it only serves the information if the browser supports the API.

**Comment by nickcox** [comment]
Sure. Here's Firefox - as mentioned, version 75.0:

![image](https://user-images.githubusercontent.com/135552/79065086-0e791400-7cf1-11ea-8b22-4c05d00dea61.png)

and here's the same page in Chrome (80.0):

![image](https://user-images.githubusercontent.com/135552/79065138-408a7600-7cf1-11ea-8eeb-25f2866d741e.png)

it looks as though Firefox does have some resource timings though:

![image](https://user-images.githubusercontent.com/135552/79065201-df16d700-7cf1-11ea-9a78-da221c65d108.png)

**Comment by Zizzamia** [comment]
So yeah, Firefox still doesn't support `paint` as `entryTypes` which is sad 😓
Try to run this simply vanilla JS code in any browser you prefer, https://plnkr.co/edit/ZSjeZb?p=preview&preview

Because this is an experimental API, Firefox will not support yet.

**Comment by Zizzamia** [comment]
So similar story for probably all other entryTypes like: `first-input`, `largest-contentful-paint`, `layout-shift`.

About `resource`, try to enable the DataConsumption API as well:
```js
resourceTiming: true,
dataConsumption: true,
```

Now that I think about it, it could be that the main problem is related to not support the `resource` type for the PerformanceObserver API.

**Comment by nickcox** [comment]
Thanks for taking the time to look into this. FWIW, I'm pretty sure the `resource` type is supported. For example, the following seems to work in the Firefox console:

```js
> PerformanceObserver.supportedEntryTypes
< Array(4) [ "mark", "measure", "navigation", "resource" ]

> function perf_observer(list, observer) { 
   console.log(list.getEntries()) 
}
< undefined

> observer = new PerformanceObserver(perf_observer)
< PerformanceObserver {  }

> observer.observe({entryTypes: ['resource']})
< undefined

> fetch('https://github.com/')
< Promise { <state>: "pending" }

(1) […]
​
0: PerformanceResourceTiming
​​
connectEnd: 45599​​
connectStart: 45599​​
decodedBodySize: 136654​​
domainLookupEnd: 45599​​
domainLookupStart: 45599​​
duration: 56​​
encodedBodySize: 41860​​
entryType: "resource"​​
fetchStart: 45599​​
initiatorType: "fetch"​​
name: "https://github.com/"​​
nextHopProtocol: "http/1.1"
​​...
```

**Comment by Zizzamia** [comment]
Would you be comfortable to debug this part of the code https://github.com/Zizzamia/perfume.js/blob/77f66638649a6dcffe2a199ab876901f42f5fa72/src/perfume.ts#L733 on Firefox? I would do the same in the next few days.

**Comment by Zizzamia** [comment]
Ok, the short story is that to enable Performance Observer for Firefox will require a major release because it could introduce some breaking changes.
I am going to start a few release candidates to test out Perfume v5 before releasing it officially.

**Comment by Zizzamia** [comment]
@nickcox here our fix https://github.com/Zizzamia/perfume.js/releases/tag/v5.0.0-rc.1 my friend ☕️
Perfume.js v5 contains some breaking changes so please feel free to open a new issue or ask me more questions if something unusual comes up.

Grazie Mille 💛
