### ISSUE TITLE
feat: Korean README

### ISSUE THREAD

**Issue by Zizzamia** [Zizzamia/perfume.js#117]
I would love to have a Korean README, so please if you know how to write one like README-ko.md it would be super awesome. Grazie Mille 💛

**Comment by ire4564** [comment]
Hello, I'm a junior developer studying open source in Korea. Your project looks great, so I'd like to translate Korean README. Can I proceed? Looking forward to a good answer. Thank you.

**Comment by Zizzamia** [comment]
Yeah my friend, go ahead 😁
