### ISSUE TITLE
Document the use with Google Analytics

### ISSUE THREAD

**Issue by zfdesign** [Zizzamia/perfume.js#121]
Following the documentation and the links from the [Articles](https://github.com/Zizzamia/perfume.js/tree/v5.0.0-rc.19#articles) section in the README.md and [this Plukr](https://plnkr.co/edit/t97Ya6?p=preview&preview) seem to suggest the use of PerfumeJS with Google Analytics. 
However I have noticed that does not seem to work in my implementation. 
Is it possible to have an example and/or clearer instructions on how to implement. 
Thank you

**Comment by Zizzamia** [comment]
Ciao @zfdesign, the implementation, and Plukr you have is related to Perfume.js v2!
I'll advise you to upgrade to `5.0.2` and use this [section in the README](https://github.com/Zizzamia/perfume.js#use-google-analytics) to have the events on Google Analytics.

To remove the confusion, I also removed the articles from the README. They are outdated and not worth to mention those anymore.

Please keep me updated if you were able to make it work. ✨

**Comment by DavidWells** [comment]
Wow, this library is super cool nice work! 

Someone DM'ed me today asking if this works with the [analytics library](https://getanalytics.io/) and I had a looksie and it does!

I just added an example of how to use `perfume.js` with the `analytics` package over [here](https://github.com/DavidWells/analytics/tree/master/examples/using-perfumejs)

When you combine `analytics` and `perfume.js` the tracking information can automatically be sent to a variety of analytics providers the person is using by attaching [this plugin](https://github.com/DavidWells/analytics/blob/master/examples/using-perfumejs/src/App.js#L16-L18)

The perfume.js analytics plugin I threw together calls `track` on any third-party script that gets [initialized in this block](https://github.com/DavidWells/analytics/blob/ef95a939f7d4393bf588dc9eed9c1458791050a3/examples/using-perfumejs/src/App.js#L19-L28) & then under the hood it's calling your [`analyticsTracker` method](https://github.com/DavidWells/analytics/blob/ef95a939f7d4393bf588dc9eed9c1458791050a3/examples/using-perfumejs/src/plugins/perfume.js#L15-L21) and fanning out the data to the various tools.

Setup a live demo over here https://analytics-perfumejs-example.netlify.app/

**Comment by Zizzamia** [comment]
Thank you @DavidWells, really appreciated ✨

Please feel free to open a PR and add your example on how to mix `analytics` with `perfume.js` in the [Perfume.js plugin section](https://github.com/Zizzamia/perfume.js#plugins). Always happy to share new ways to use Perfume.js in the web community. 🚀🌕

Oh btw, the **Netlify** link is not up anymore. 😅

**Comment by DavidWells** [comment]
Fixed all the links and made an official analytics plugin for this 🎉

https://github.com/Zizzamia/perfume.js/pull/122#issue-421727234

**Comment by Zizzamia** [comment]
Amazing, now we can close this issue. If anyone has more questions related to external Analytics, please open a new issue.
