### ISSUE TITLE
Trim down not necessary mangle properties in Terser

### ISSUE THREAD

**Issue by Zizzamia** [Zizzamia/perfume.js#125]
To boost the minification we have some mangle properties in the Terser config.
https://github.com/Zizzamia/perfume.js/blob/master/rollup.config.ts

But over time we stopped using most of them, I think it's time to double-check which one are the properties are not necessary anymore.

**Comment by wadjoh** [comment]
@Zizzamia Looks like the mangle properties have been removed from the rollup config in this commit: https://github.com/Zizzamia/perfume.js/commit/310afaef23f8af3b608a71ff1cce34bfd0c57eaf

Is this ticket still relevant?

**Comment by Zizzamia** [comment]
Yeah not relevent anymore.

I just found really hard to keep up with the tuning of Terser. Let me close the ticket, but if you have any idea on how to keep optimizing the trim down, I am all ears.

**Comment by wadjoh** [comment]
> I just found really hard to keep up with the tuning of Terser.
Like in terms of performance? Asking because it seems like the current Terser config is pretty minimal.

**Comment by Zizzamia** [comment]
> Like in terms of performance?

Oh I am talking about the configuration I was running. Btw if you have any advice on how to improve the usage for Perfume,  please feel free to share a PR.

Also love some help to polish this library.

**Comment by Hi2885** [comment]
Report
