### ISSUE TITLE
The name "myAnalyticsTool" could not be found

### ISSUE THREAD

**Issue by chengmings** [Zizzamia/perfume.js#132]
When I copied Quick start, it told me that the name "myAnalyticsTool" could not be found
why？

**Comment by Zizzamia** [comment]
Did you change `myAnalyticsTool` with your analytics tool?

**Comment by chengmings** [comment]
> Did you change `myAnalyticsTool` with your analytics tool?

No，I downloaded this library directly, and then copied the content on Quick start

**Comment by Zizzamia** [comment]
`myAnalyticsTool` is a placeholder, for your favorite analytics tool to send the metrics Perfume collects for you 😄

**Comment by chengmings** [comment]
> Perfume
Do you mean I need to find an analysis tool to work with Perfume?
What analysis tools do you generally use？

**Comment by Zizzamia** [comment]
Perfume is not an analytics tool with dashboard or a database to save your data, it is simple a way to gather performance field data, then you need to save this data anywhere you prefer. Popular choice are Google Analytics, Amplitude, Datadog, Mixpanel, etc...

**Comment by Zizzamia** [comment]
If you have Google Analytics in your project you should check out this part of the doc https://github.com/Zizzamia/perfume.js#use-google-analytics.

I'm going to close this issue, because we already covered on several points related to your question. Have a great week.
