### ISSUE TITLE
Expose aggregated metrics when all are available

### ISSUE THREAD

**Issue by rikonor** [Zizzamia/perfume.js#133]
Hi,

Thank you for creating this. I was wondering - do you see a way to expose a callback that can be called with all metrics aggregated once they are available? This would complement the individual metrics firing.

The use-case for this is reporting all metrics at once, instead of as they come.

I tried my hand at doing this myself - since it seems most metrics fire at or before the page changes state to hidden, I added an event handler for visibility change. I also collect the metrics into a `measurements` object as they come via the analytics tracker. See the example:

```js
let ranOnce = false;
  addEventListener("visibilitychange", () => {
    if (!ranOnce && !!document.hidden) {
      publish("measurements", {
        pageUrl: location.toString(),
        ...roundNumbers(measurements),
      }) || (ranOnce = true);
    }
  });
```

That said, it seems like there's a lot of fragmentation in browser support for `visibilitychange`. (See `hidden` vs `msHidden` vs `webkitHidden`, etc at [Page Visibility API on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API). Curious if and how you ended up handling it in this project.

Thanks again.

**Comment by Zizzamia** [comment]
Ciao @rikonor, thank you for the feedback.

The problem in waiting all metrics are ready, it creates a ton of risk in not firing some of the late values in case someone bounce very quickly out of the website.

You are ofcourse free to aggregate Perfume metrics how and when you prefer in your application. It is something Perfume would never try to push an opinionated API for it.

If I was trying to achieve your goal I will probably pick a metric like `tbt` and wait that happens, but again you might risk to miss a ton of other values if the user leaves the page in the first 10s.
