### ISSUE TITLE
'storage.estimate' is not a function

### ISSUE THREAD

**Issue by glebv** [Zizzamia/perfume.js#135]
Hi, I discovered that perfumejs(v5.0.2) leads to issue "storage.estimate is not a function".  
The issue was discovered on Mobile Chrome (55-60).
[The code ](https://github.com/Zizzamia/perfume.js/blob/930f637d52b365fea049d47bea09206be9327dda/src/perfume.ts#L57) is corresponding to the issue.

Probably it can be solved by
```
if (WN && WN.storage && typeof WN.storage.estimate === 'function') { 
       WN.storage.estimate().then(reportStorageEstimate); 
}
```

Can I help with it and prepare PR?
Thanks for maintaining the helpful library!

**Comment by Zizzamia** [comment]
Thank you @glebv for reporting this issue! Yes please, would love to have a PR from you than I will take care for release the next version.

**Comment by Zizzamia** [comment]
@glebv one small ask, can you make sure to add a test that recreates the issue and then fix it. Thank you!

**Comment by glebv** [comment]
Yeap, I'll do it

**Comment by glebv** [comment]
I've prepared a fix but I don't have enough permissions to create a branch and PR, should I fork the repo with my fix?
PS package.lock in master has old version (5.0.2) instead of 5.1.0, I've fixed in my pr as well

**Comment by Zizzamia** [comment]
Yes @glebv, you need to fork and create a PR from your fork. Also don't worry about the version in the `package.lock`, keep the PR simple and focus only on the issue you discovered. Thank you again for doing this.

**Comment by glebv** [comment]
Hi @Zizzamia, when are you going to release next version?

**Comment by Zizzamia** [comment]
@glebv sorry for the late reply. In the next couple of days I will release the new version 🎉
