### ISSUE TITLE
Measure TBT independent of FID

### ISSUE THREAD

**Issue by kevinkimball** [Zizzamia/perfume.js#140]
Thanks for your library.

I am doing lab measurements, and I thought it would be useful to measure the TBT without relying on user input. This would make it usable in the lab as a proxy for FID. 

web.dev [defines FID](http://web.dev/tbt) as 
> The Total Blocking Time (TBT) metric measures the total amount of time between First Contentful Paint (FCP) and Time to Interactive (TTI) where the main thread was blocked for long enough to prevent input responsiveness. 

My suggestion is to change the library to match that calculation.

**Comment by Zizzamia** [comment]
Ciao @kevinkimball,
thank you for making this suggestion.

Perfume.js focus on field data not lab data. If you are looking to collect Lab Data I suggest to use Lighthouse CI instead. I personally use it in combination with Lighthouse Server, and it's pretty great. cc @patrickhulce did some incredible work there.

Happy to share more on how to use TBT with Perfume.js in the field.

**Comment by patrickhulce** [comment]
There has been *some* discussion around a field equivalent of TBT using [long task performance observers](https://github.com/w3c/longtasks). I think it would still be an interesting exploration under another name but understood if you want to keep it out of scope for perfume.js :)

**Comment by Zizzamia** [comment]
@patrickhulce Perfume.js has three TBT options:
1. measure long tasks from FCP until FID
2. measure long tasks from FCP until FID + 5 seconds
3. measure long tasks from FCP until FID + 10 seconds

I use all of them at Coinbase, and I realized the number 3 option works really well. In some way waiting 10 extra seconds after FID it normalize the data for Total Blocking Time in the field.

**Comment by Zizzamia** [comment]
I think the key part of the story is that using any polifyll to calculate Time To Interactive is extremely expensive in resources need it, and not simple enough that is worth to use in the field.

That's why we stopped using https://github.com/GoogleChromeLabs/tti-polyfill and instead we rely on FID from now on.

**Comment by patrickhulce** [comment]
Ah that's really cool I didn't realize you had options 2 and 3 there! 👍  Makes sense to exclude the TTI polyfill at this point. Your solutions sound great :)
