### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by suntong** [Zizzamia/perfume.js#141]
Is perfume.js portable? It seems perfume.js is build for nodejs apps, but is it possible to use it in other code bases, e.g., the sites build with C#, or modern Go, or even to Mobile measuring? thx.

**Comment by Zizzamia** [comment]
Interesting question, can you share more info, maybe what's the end result you are looking for.

**Comment by suntong** [comment]
Hi, 

Thanks for the response.

All those measures that `perfume` collects, like First Paint (FP), First Contentful Paint (FCP), First Input Delay (FID), Total Blocking Time (TBT), etc, are very interesting metrics, that I need a systematic way to measure, instead of relying on other tools like lighthouse, etc. 

So, would it be possible, for the html file to include a `perfume.js` file so that all such metrics can be sent/collected, just like how lighthouse collect them for itself, without developers manually marking each point with `perfume.xxstart`, `perfume.xxend` etc, just like include a `jquery.js` file and the html page can make use of jquery?

Then, no matter what kind of back end server it is, be it node, or Go or C#, as long as the served `.html` include the `perfume.js` file, it'll work. That's what I was hoping for, and wasn't sure even after reading the README several times. 

Thanks

**Comment by Zizzamia** [comment]
Right, the README could offer more infos, that's for sure (feel free to open a PR 😄)

So for your case, do you have an internal endpoint to connect Perfume.js with your product?
Like ideally what you will end up to do is something like

```js
const trackMetric = (metricName, data, vitalsScore) => {
    const metric = {
      metric_name: metricName,
      data,
      vitals_score: vitalsScore || null
    };
    const body = JSON.stringify(metric);
    // Use `navigator.sendBeacon()` if available, falling back to `fetch()`.
    (navigator.sendBeacon && 
       navigator.sendBeacon('/analytics', body)) ||
       fetch('/analytics', {body, method: 'POST', keepalive: true});
}

new Perfume({
  analyticsTracker: options => {
    const {
      metricName,
      data,
      vitalsScore,
    } = options;
    switch (metricName) {
      case 'fidVitals':
        trackMetric('web_vitals_fid', data, vitalsScore);
        break;
      case 'lcp':
        trackMetric('web_vitals_lcp', data, vitalsScore);
        break;
      case 'cls':
        trackMetric('web_vitals_cls', data, vitalsScore);
        break;
      case 'tbt10S':
        trackMetric('web_vitals_tbt', data, vitalsScore);
        break;
    }
  },
});
```

Remember, Perfume.js just collects data for you, then you decide where to store the data and how to visualize them. There are so many third party provider you can use to collect and visualize the data: Google Analytics, Datadog, Mixpanel, Amplitude, etc...

**Comment by suntong** [comment]
Cool. Sorry I'm not a JS programmer, so when you (the README) are/is talking to me with JS code, I'm slow to understand what you are saying, :) 
It's a mouthful for me now. Let me try to digest them slowly...
thx again
