### ISSUE TITLE
Custom metrics

### ISSUE THREAD

**Issue by alaingoga** [Zizzamia/perfume.js#142]
We are using the library to collect core vital and send them to google analytics using GTM. But we would like to send other custom performance metrics like hydration time on react. There is a way to extend the library to allow this? 
It would be ideal to follow the same flow.

**Comment by Zizzamia** [comment]
Ciao @alaingoga,
have you tried to use `perfume.start` and `perfume.end` to annotate custom [performance metrics](https://github.com/Zizzamia/perfume.js#annotate-metrics-in-the-devtools)?

I personally use it all the time for any particular JS logic I want to monitor over time, both in the Chrome Dev Tools and in the field.

**Comment by Zizzamia** [comment]
Closing this issue as lack of replies.
