### ISSUE TITLE
respect doNoTrack

### ISSUE THREAD

**Issue by klh** [Zizzamia/perfume.js#146]
if navigator.doNotTrack is true, the abort the tracking

**Comment by Zizzamia** [comment]
Oh wow, I wasn't aware that was a thing. Thank you for the feedback.
I wonder if the read of this API should be done from the developer side or library side, it could cause some edge cases where a third party sets this to false and then Perfume stops to working and the developer is not aware of why.

Also if we are worry to sending the data to your company analytics when `doNotTrack` is `true`, you can just have an `if` statement inside the `analyticsTracker` callback.

**Comment by Zizzamia** [comment]
Closing this issue as explained here https://github.com/Zizzamia/perfume.js/pull/147#issuecomment-722586782 that this should not be part of Perfume.js but more a custom logic the developer should implement inside the `analyticsTracker` callback.
