### ISSUE TITLE
ie11 / platform support

### ISSUE THREAD

**Issue by klh** [Zizzamia/perfume.js#148]
if you either 
a: polyfilled .includes
or b: avoided using it at all
perfume would work in ie11.

as it is now it breaks.

examples of usages:
['slow-2g', '2g', '3g'].includes(et)

polyfill:
```

if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';

    if (search instanceof RegExp) {
      throw TypeError('first argument must not be a RegExp');
    } 
    if (start === undefined) { start = 0; }
    return this.indexOf(search, start) !== -1;
  };
}
```

**Comment by Zizzamia** [comment]
Oh interesting, maybe I can avoid using `includes` and use `indexOf` instead. What do you think?

**Comment by klh** [comment]
Sure, should be pretty simple, the only place you really use includes is for testing the network type stuff - so its not a big refactor - but i thought it better to let you take the decision on codechange or polyfill.

a simple switch statement would work aswell.

**Comment by knoxjeffrey** [comment]
Hello, thank you for making this change and I see it is merged in. However, when I update perfume.js I can still see the `.includes` in the dist folder. Does the update need published to npm?
