### ISSUE TITLE
Increase CLS accuracy

### ISSUE THREAD

**Issue by bzikst** [Zizzamia/perfume.js#149]
First of all, thank you for a great library! I'd like to suggest one improvement.

In example code for external analytics you multiply CLS data by 1000 to avoid floats. This is the same thing I do for my own analytics tracking system. But I'm getting anyway precise of two digits after period because of roundByTwo function call in logMetric. This is especially important for CLS because it's common value is like 0.01432. Can you please increase CLS logging accuracy? Maybe by using something like roundByFour for CLS.

**Comment by Zizzamia** [comment]
Ciao @bzikst, great point!
I can work on it next week, but if you want open a PR sooner I'm happy to merge it.
Just make sure to have all the tests for it 😁

**Comment by bzikst** [comment]
Thank you @Zizzamia! I'll wait for your fix :)

**Comment by Zizzamia** [comment]
Sorry for the delay https://github.com/Zizzamia/perfume.js/commit/137d153571cea72be457b7d3b8bc9355606b36ea, this improvements is now part of `v6.1.0` 😄
