### ISSUE TITLE
It's possible to send just one tracking event?

### ISSUE THREAD

**Issue by victorjspinto** [Zizzamia/perfume.js#154]
Hi Guys. First of all, congratulations for this amazing project.

Here at my company, we uses a custom made event tracking platform. Would it possible to aggregate all metrics into a unique event per page view?

That way, I avoid overload this system with a bunch of events :)

Anyone already had this doubt?

best,
victor

**Comment by asvae** [comment]
We implemented it as:

```typescript
await lcpFinalTriggered
await clsFinalTriggered
await tbtFinalTriggered
```

Which I'm not sure is the right way. Would be nice to have this integrated in perfume somehow. Maybe even as an event:

```typescript
new Perfume({trackingDone: callback})
```

**Comment by Zizzamia** [comment]
Ciao @victorjspinto, so the key part of the story is that all metrics happen at different moment of the loading experience, so create just one metrics that joins them all will cause potential data drops if fired too late.

I understand you don't want to overload the system, my best advice is to aggregate them as you best wish in your analytics tooling.

Perfume.js should not provide bias on when the data is reported, but only a nice integration with the public APIs. When the data should be reported I think it is still fair to leave this freedom to you as the ultimate customer.

**Comment by Zizzamia** [comment]
Closing this issue as has been more than year from last conversation.
