### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by knoxjeffrey** [Zizzamia/perfume.js#155]
#148 

Hello, thank you for making the change to support IE11 in the attached issue and I see it is merged in. However, when I update perfume.js I can still see the .includes in the dist folder. Does the update need published to npm?

**Comment by Zizzamia** [comment]
Good morning @knoxjeffrey, I just publish v6 with all latest PRs. Can you please let me know if that fixed your issues, please.

**Comment by knoxjeffrey** [comment]
Sorry for not getting back to you on this, that's all sorted, thank you 👍
