### ISSUE TITLE
How can I get a http api time?

### ISSUE THREAD

**Issue by jackchoumine** [Zizzamia/perfume.js#180]
I want to know all http api response time in my project, does it support it? How can I do it?

**Comment by Zizzamia** [comment]
Ciao @jackchoumine how you doing?
That metric doesn't come for free, you probably want to use the `perfume.start` and `perfume.end` to manually annotate how long it will take each API.

Let me ask you a few questions:
- what's your goal in measuring this?
- do you want to measure all APIs or just some?

**Comment by jackchoumine** [comment]
> Ciao @jackchoumine how you doing? That metric doesn't come for free, you probably want to use the `perfume.start` and `perfume.end` to manually annotate how long it will take each API.
> 
> Let me ask you a few questions:
> 
> * what's your goal in measuring this?
> * do you want to measure all APIs or just some?

1. The goal it to know all api time 
2. All api in projects 

I am try to improve a old project  I wanna find what http api is slow so I wanna all api time
