### ISSUE TITLE
Resource timings buffer extension 

### ISSUE THREAD

**Issue by vxd-dev** [Zizzamia/perfume.js#181]
Hi,

I have noticed that it is possible to track performance of small number of requests/resources. Any plans to support setResourceTimingBufferSize/clearResourceTimings API? Is there any chance to build a workaround to use it with current version (if it is possible).

Thank you.

**Comment by Zizzamia** [comment]
Oh interesting, https://developer.mozilla.org/en-US/docs/Web/API/Performance/setResourceTimingBufferSize!
Help me better understand, what would be the goal to use this API?

Happy to add something on it for Perfume, just trying to connect the dots on how the community will use it and why.
