### ISSUE TITLE
Question about Interaction to Next Paint (INP) implementation

### ISSUE THREAD

**Issue by SuperOleg39** [Zizzamia/perfume.js#194]
Hello!

Do you have a plans for [Interaction to Next Paint (INP)](https://web.dev/inp/) metric implementation?
Looks like implementation can be non-trivial, according to [web-vitals package implementation](https://github.com/GoogleChrome/web-vitals/blob/next/src/onINP.ts).

I am interested in your opinion on this metric, as it will affect the size of the package badly, but it seems that this metric still have to start collecting in the future.

**Comment by SuperOleg39** [comment]
@Zizzamia hello! What do you think?

**Comment by Zizzamia** [comment]
Ciao @SuperOleg39, thank you for the ping and sorry for the late reply.

Something I am been thinking for quite a while if it's time to make Perfume.js a superset of the Web Vitals package, by importing the package into Perfume and add some extra functionality on top of it.

This will help stay always align with Google updates, and also keep the extra features that Perfume wants to experiment and offers.

What's your thoughts on this?

**Comment by SuperOleg39** [comment]
Hi! Thanks for the answer)

I see only one problem about `web-vitals` integration - result package size, because at this moment `web-vitals` have 2.5kb gzip size, аnd `perfume.js` is 2.3kb gzip (Bundlephobia info).

What do you think to `size-limit` integration before?

**Comment by SuperOleg39** [comment]
@Zizzamia another reason to add `web-vitals` - https://github.com/GoogleChrome/web-vitals/blob/main/CHANGELOG.md#v300-2022-08-24

"Report TTFB after a bfcache restore" and new "attribution build" looks like very important and useful.

**Comment by Zizzamia** [comment]
Yeah, I think Perfume.js is better suited to be a superset of web-vitals going forward. Going to make the change pretty soon. Just need to find a few hours to make the switch.

Recently I got distracted on building a Performance library for React Native. But now I am back with more coding time on my hands.

**Comment by Zizzamia** [comment]
Alright, now Perfume.js is a super set of Web Vitals, starting from [v8.0.0](https://github.com/Zizzamia/perfume.js/releases/tag/v8.0.0).

Please, if you see anything that is not working let me know and I will take care of it.

**Comment by SuperOleg39** [comment]
Thank you! Will try to integrate soon.

**Comment by SuperOleg39** [comment]
Only one problem, now `perfume` is 5kb gzip.

But I think than lazy loading solves this problem partially.

**Comment by SuperOleg39** [comment]
Looks like First Paint is unsupported in `web-vitals`

**Comment by SuperOleg39** [comment]
About `Cumulative Layout Shift`, there is a big change, when CLS fired after page visibility changed to hidden.

It is mean than we can send this metrics only when user leave page twice.

Maybe `reportAllChanges ` for CLS will be a good default? https://github.com/GoogleChrome/web-vitals/pull/283

**Comment by SuperOleg39** [comment]
> About Cumulative Layout Shift, there is a big change, when CLS fired after page visibility changed to hidden.

The same behaviour with Total Blocking Time

For now it is impossible to collect this metrics when user closing page, if batching is used https://github.com/GoogleChrome/web-vitals#batch-multiple-reports-together

**Comment by SuperOleg39** [comment]
@Zizzamia maybe we start with this changes - https://github.com/Zizzamia/perfume.js/pull/208/files

About TBT, looks like it fired 10+ seconds after FID (expect 5 second because of https://zizzamia.github.io/perfume/#/total-blocking-time/) - so nothing to change here)

**Comment by Zizzamia** [comment]
You right! The fact Perfume does not handle on his on Change Visibility, it does introduce a regression. Which is not good, and makes the data quite unuseful.

I am going to introduce back some fo the code related to Change Visibility that we used to have, and release a new version by the end of the year.

Thank you for keep trying Perfume.js!!!!
Making Perfume.js a superset of web-vitals will require some extra love to make it right. ✨

**Comment by SuperOleg39** [comment]
Will waiting for https://github.com/GoogleChrome/web-vitals/issues/180#issuecomment-1344720373

**Comment by Zizzamia** [comment]
@SuperOleg39 your work in testing both libraries is just the best OSS Christmas present. Thank you man.

I reverted some of the changes I initially made, and trying to recover the initial value of Perfume.js but still keeping the library as superset of web vitals.

https://github.com/Zizzamia/perfume.js/releases/tag/v8.1.6

Let me know if looks better on your side, and love your testing in making Perfume.js better. I will make sure to prioritize your advice going forward.

**Comment by SuperOleg39** [comment]
Thank you for all this work!)

Test https://github.com/GoogleChrome/web-vitals/issues/180 PR with `perfume.js@8.2.0` and `reportAllChanges` for CLS and INP - this metrics works perfect for my case!

Have only trouble with TBT - looks like this metric stop reported?

**Comment by SuperOleg39** [comment]
Looks like TBT not reported, when:

- page loaded
- some action, FID is reported
- immediately leave page (not wait for 10 second for TBT report)
- back to the page again
- TBT will never be reported

**Comment by SuperOleg39** [comment]
Found this code https://github.com/Zizzamia/perfume.js/blob/master/src/log.ts#L42

**Comment by Zizzamia** [comment]
Yeah the case you described is expected!
That's because the reporting to be accurate Perfume needs to wait the 10s to be over.

Glad Perfume, now works well for you.
Please let me know if there is anything I can help you with more.

**Comment by SuperOleg39** [comment]
Thanks for the explanation)
