### ISSUE TITLE
web-vitals navigationType support

### ISSUE THREAD

**Issue by SuperOleg39** [Zizzamia/perfume.js#209]
Looks like we need to send `navigationType` parameter to `analyticsTracker` callback.

Any metrics from `web-vitals` will have this property.

Will try to implement myself first)

**Comment by Zizzamia** [comment]
Sweet, let me know when the PR is ready and I will review it right away.

**Comment by SuperOleg39** [comment]
Added `navigationType` to all web-vitals metrics - https://github.com/Zizzamia/perfume.js/pull/210/files

**Comment by Zizzamia** [comment]
Approved, the only thing missing is updating the README, and than we can publish it.
I am happy to update the README if you want, or I leave the honor to you.

**Comment by SuperOleg39** [comment]
It will be enough? https://github.com/Zizzamia/perfume.js/pull/211

**Comment by Zizzamia** [comment]
Published to https://github.com/Zizzamia/perfume.js/releases/tag/v8.3.0
