### ISSUE TITLE
Disable requestIdleCallback for CLS and INP reports

### ISSUE THREAD

**Issue by SuperOleg39** [Zizzamia/perfume.js#213]
**Problem**

CLS and INP reported from `web-vitals` when page visibility is changed.
In perfume.js reports [wrapped in `requestIdleCallback`](https://github.com/Zizzamia/perfume.js/blob/master/src/utils.ts).
If you are [batching multiple reports](https://github.com/GoogleChrome/web-vitals#batch-multiple-reports-together), and send it also in `visibilitychange` callback, this metrics never be reported if page will be closed, because report will be fired after this callback.

**Solution**

We can unwrap CLS and INP reports from `requestIdleCallback` - it is not a problem for performance, because already hapenned in backgroud.

PR - https://github.com/Zizzamia/perfume.js/pull/212

**Comment by SuperOleg39** [comment]
@Zizzamia review please)

**Comment by Zizzamia** [comment]
Left a review, you just need some tests and than we are ready to merge it and publish it.
Thank you for your great support!

**Comment by SuperOleg39** [comment]
Thanks, will waiting for the publication :)

**Comment by SuperOleg39** [comment]
@Zizzamia Hi! Want to ask you for this changes publication)

**Comment by Zizzamia** [comment]
Yes sorry, I am going to release the new change in two hours.
Thank you for your flexibility.

**Comment by Zizzamia** [comment]
Done https://github.com/Zizzamia/perfume.js/releases/tag/v8.4.0
Happy Friday
