### ISSUE TITLE
TotalBlockingTime wrong reports

### ISSUE THREAD

**Issue by SuperOleg39** [Zizzamia/perfume.js#214]
**Problem**

[initTotalBlockingTime](https://github.com/Zizzamia/perfume.js/blob/master/src/totalBlockingTime.ts) called multiple times, with same performance entries, and all entries calculated together - after update we can see significantly increased TBT metrics

**Comment by SuperOleg39** [comment]
Fix - https://github.com/Zizzamia/perfume.js/pull/215

**Comment by Zizzamia** [comment]
Merged your fix and published a new release https://github.com/Zizzamia/perfume.js/releases/tag/v8.3.0
