### ISSUE TITLE
Cannot read properties of undefined (reading 'requestStart') on navigation with bfcache

### ISSUE THREAD

**Issue by meskill** [Zizzamia/perfume.js#220]
I'm getting the error from the title on [this line](https://github.com/Zizzamia/perfume.js/blob/master/src/observe.ts#L22) when testing bfcache in chrome browser.

## Reproduction

1. Open Chrome DevTools -> Application -> Back/Forward Cache
2. Click `Test Back/Forward cache`

![image](https://user-images.githubusercontent.com/8974488/216551436-f2e4ee38-395f-4aaa-8776-da0cba8c661f.png)

**Comment by SuperOleg39** [comment]
Initial problem from web-vitals package - https://github.com/GoogleChrome/web-vitals/issues/313

**Comment by SuperOleg39** [comment]
Following the discussion in `web-vitals` repo, we can still report `0` values and add just fix for BFCache case - https://github.com/Zizzamia/perfume.js/pull/221

**Comment by scamden** [comment]
i believe we are hitting this error as well fwiw

```
undefined is not an object (evaluating 'e.entries[0].requestStart')
```

**Comment by Zizzamia** [comment]
@scamden what version are you using?

**Comment by scamden** [comment]
8.4.0, should i try an upgrade?

**Comment by scamden** [comment]
I'm upgrading to 9.4 and will let you know if we see again

**Comment by Zizzamia** [comment]
Also, curios, what version of `web-vitals` are you resolving, maybe we need to upgrade from Perfume side as well.

**Comment by scamden** [comment]
> Also, curios, what version of `web-vitals` are you resolving, maybe we need to upgrade from Perfume side as well.

@Zizzamia we have 3.5.2 for web vitals

**Comment by scamden** [comment]
prior to the upgrade 3.4.0 fwiw

**Comment by scamden** [comment]
Haven't seen it since to my knowledge (although we had only seen it once so sample size is pretty low for this data :P )

Thanks for the tip on upgrading! Perfume is a great package :)

**Comment by Zizzamia** [comment]
Ok, so I think it's safe to close this for now.

I will reopen this if this issue happens again.
