### ISSUE TITLE
Generic analytics platform support

### ISSUE THREAD

**Issue by lifeisfoo** [Zizzamia/perfume.js#24]
Hi @Zizzamia, what about a configurable analytics function to use perfume.js with any platform?

Changing the `sendTiming` function in this way should be enough:

```
  private sendTiming(metricName: string, duration: number) {
    if (!this.config.analyticsLogger) {
      return;
    }
    const durationInteger = Math.round(duration);
    this.config.analyticsLogger(metricName, duration)
  }
```

## Example using google analytics
```
  const perfume = new Perfume({
    analyticsLogger: (metric, duration) => {
      window.ga("send", "timing", metric, "name", duration);
    }
  });
```

## Example using matomo (ex piwik)
```
  const perfume = new Perfume({
    analyticsLogger: (metric, duration) => {
      _paq.push(['trackEvent', 'performance', 'timing', metric, duration])
    }
  });
```

In this way you can also:
- replace the entire analytics configuration block with a single property
- clean up the library code from the global analytics variable

P.s.
great talk at codemotion Rome

**Comment by Zizzamia** [comment]
Grazie for feature propose, 🙏
I love the idea of having a public `analyticsLogger` method, and at the same time, I believe it's essential to keep the original config for Google Analytics usage (I like a simple popular scenario with the possibility to extend the library for other cases). 

Feel free to start a PR 😊
Cheers 🍻

**Comment by Andarist** [comment]
GA is a specific use case that can be easily implemented in user land. I agree with @lifeisfoo that it should be decoupled from the core library, if one don't want to use GA he/she still has to get built-in `sendTiming` implementation which costs some bytes.

**Comment by Zizzamia** [comment]
Added to Perfume v0.7.1 under [Analytics Support](http://zizzamia.github.io/perfume/#/analytics-support/)! 😄
I'm going to keep the Google Analytics support as default version, with the possibility to expand Perfume to other analytics platforms.

Thank you again for the feedback, you guys are the best 👊
