### ISSUE TITLE
Add FID (First Input Delay)

### ISSUE THREAD

**Issue by kurtextrem** [Zizzamia/perfume.js#33]
https://github.com/GoogleChromeLabs/first-input-delay

**Comment by Zizzamia** [comment]
Amazing, I added on the [v0.8.0](https://github.com/Zizzamia/perfume.js/milestone/15) milestone!
👨‍🚀🚀🌕
cc @philipwalton

**Comment by Zizzamia** [comment]
Hey hey, you can find FID from [v0.9.0](http://perfumejs.com) version, just released.

**Comment by kurtextrem** [comment]
Great, thank you!!!
