### ISSUE TITLE
Won't seem to fire when cache disabled

### ISSUE THREAD

**Issue by benmccallum** [Zizzamia/perfume.js#38]
Just added this into the <head> of my site. Doing an F5 with 'Disabled cache' checked in Chrome DevTools nothing gets written to the console. Unchecked, I see the PerfumeJs messages with timings. Does the script have to load before something else? 

I haven't got it on production yet, but will soon-ish, so will be able to send you the link to repro. Just thought I'd ask.

**Comment by Zizzamia** [comment]
This is interesting, please keep me updated with the production version.
What metrics are you collecting, FCP / TTI / CFP? 

I use Perfume in production in my company https://getplan.co/ (you need to login in) 😄

**Comment by benmccallum** [comment]
Collecting all metrics, just basically default settings with GA user timings enabled. Should be on prod soonish so I'll shoot the link over when it's up if it's still a problem. :)

**Comment by dance-cmdr** [comment]
Hi @Zizzamia, I think I experienced something similar. TTI didn't fire consistently with Disabled Cache on Chrome.

**Comment by Zizzamia** [comment]
It might be related with the https://github.com/GoogleChromeLabs/tti-polyfill that Perfume uses to calculate the TTI.
In what case do you need to run the website with "Disabled Cache on Chrome"?
Is it for pure debugging?

Thank you for the feedback, I need to also work on https://github.com/Zizzamia/perfume.js/issues/33 anytime soon.

**Comment by benmccallum** [comment]
That being said, still seems to fire haphazardly. Would like to keep this open a little longer while I monitor.

**Comment by Zizzamia** [comment]
Thank you @benmccallum, I agree! I recently fixed https://github.com/Zizzamia/perfume.js/issues/40 which avoids firing Metrics when the tab is closed.
Let me prepare the next version, so we can start testing it!

**Comment by Zizzamia** [comment]
*v0.8.1* is out 🔥 🚀
