### ISSUE TITLE
Support Google Analytics being loaded async

### ISSUE THREAD

**Issue by benmccallum** [Zizzamia/perfume.js#42]
We're loading GA via GTM which is added as an async script tag. As such, Perfume is logging a warning that GA hasn't been loaded in time. I think my scenario is pretty common, so can we address this as part of perfume?

**Implementation thoughts**
I guess we'd need to maintain a queue of `ga` calls in perfume, with a setInterval polling for GA every second up to a configurable maximum. 

So we could introduce two more settings, something like:
* gaPollingInterval
* gaPollingMaximumAttempts

Add some private vars:
* gaQueue
* gaPollingAttempts
* gaPoller

In trackTiming function, detect as it is now for window.ga but if not defined, add current timing request to queue and define gaPoller as a setInterval if not already with new settings.

Create gaPoller/setInterval callback that:
* Tries to check for window.ga again and fire off timings
* Increments gaPollingAttempts
* If gaPollingAttempts > gaPollingMaximumAttempts, cancel setInterval

It's not ideal, but I can't see any other way around it. Alternative would be to define ga function ourselves, like they do in their snippet before loading the library, but that seems dodgy if they ever change their implementation.

What do you think? Happy to implement it myself and submit a PR if you agree with the above.

**Comment by Zizzamia** [comment]
I would like to avoid any sort of `setTimeout` or `setInterval` because the Angular framework fires an extra change detection after each one of them.
We could simplify the approach by having one public setting and one method, like:
```ts
const perfume = new Perfume({
  gaAsync: true
});
```
and as you said it will start queuing the Metrics, when `ga` is available we will call
```ts
perfume.gaResolve();
```
and resolve the queue.

Am I missing anything?
If you can work on a PR would be amazing! 🙌
What frameworks and product are you using/building (just for curiosity)? 🚀

**Comment by Zizzamia** [comment]
I moved this refactor to `v0.9.1`; this will give us some extra time to don't rush the design implementation. I'm looking forward to work on your proposal.

**Comment by benmccallum** [comment]
No worries. It's done, just trying to figure out how to commit with all the precommit checks. Seems like a lot of the failures were existing? Not sure how you managed to commit/push.

**Comment by benmccallum** [comment]
Managed to get through them all, turns out they were all mine. Will open up the PR now, but haven't actually run the changes in the browser yet.

Will probably rename GaQueueItem and gaQueue to something else. Maybe GaSend and gaSendQueue. Let me know what you think. Don't think we need a gaAsync: true config flag, that'd just be all internals.

**Comment by Zizzamia** [comment]
I believe we need to create a generic **queue** system, that can be used from external tracking services too.

**Comment by benmccallum** [comment]
So you mean if someone passes in their own customer analytics tracker, it queues up requests for those services too? 

Can define a common interface like `IAnalyticsTracker`, that has members `HasLoaded` and `Track`? Then create a `GoogleAnalyticsTracker : IAnalyticsTracker` and others can implement their own?

**Comment by benmccallum** [comment]
Note to self: `.pop()` off the queue rather than just loop over.

**Comment by Zizzamia** [comment]
Yes, in the past we had people requesting "Generic analytics platform support" #24.
Google Analytics will always be the default choice, and Perfume is going to expose the metrics to any tracking service you will end up to use.

I will keep the design conversation in the https://github.com/Zizzamia/perfume.js/pull/43
