### ISSUE TITLE
TTI polyfill head script

### ISSUE THREAD

**Issue by a-axton** [Zizzamia/perfume.js#44]
Is the TTI polyfill head script required? I was noticing that events weren't firing every page load. Once I added the head script from the TTI readme it seemed to be firing 100% of the time. If this is required should it be added to the docs somewhere?

This is the script I'm referring to from https://github.com/GoogleChromeLabs/tti-polyfill
```
<script>
!function(){if('PerformanceLongTaskTiming' in window){var g=window.__tti={e:[]};
g.o=new PerformanceObserver(function(l){g.e=g.e.concat(l.getEntries())});
g.o.observe({entryTypes:['longtask']})}}();
</script>
```

**Comment by Zizzamia** [comment]
Oh Boy, it is interesting that I never noticed this bug! Thank you for pointing this out.
Can you please share with me more info on how big is your app (kb/mb), how you load the resources in your `index.html` and how you use **Perfume**. This information would be beneficial to me to understand better your case.

And I will also double test it, and see to introduce back the code inside Perfume.

**Comment by Zizzamia** [comment]
@a-axton v1.0.0 is out 🔥 🚀 with your fix
