### ISSUE TITLE
Unable to use as an ES6 module

### ISSUE THREAD

**Issue by Artur-** [Zizzamia/perfume.js#53]
```
import Perfume from 'perfume.js';
```

results in

```
Uncaught SyntaxError: The requested module '../../tti-polyfill/tti-polyfill.js' does not provide an export named 'default'
```

**Comment by Zizzamia** [comment]
Thanks for opening this issue.
How do you bundle your app? Do you use Webpack?
Would you mind give more context about your app, please.

**Comment by Artur-** [comment]
No bundling
No webpack

Just a module import

**Comment by Zizzamia** [comment]
Lol 🤔
What if you use the other two solutions of imports?

Additionally, you can import the transpiled modules from dist/es in case you have a modular library:
```js
import Perfume from 'node_modules/perfume.js/dist/es/perfume';
```

Universal Module Definition:
```js
import Perfume from 'node_modules/perfume.js/perfume.umd.js';
```

**Comment by Artur-** [comment]
It does not matter which import is used. 

I guess the problem is that `tti-polyfill` is not an ES module

**Comment by snipsy** [comment]
Hello,

I have similar problem, tried to use perfume.js in my es6 app, tried to include files from angular folder inside perfume.js but my app could not transpile ES module.

I've also tried several umd.js files in different versions but nothing worked.

I've also tried including perfume.js from dist/lib folder and after providing all necessary dependencies my app successfully started but I am not getting measures from perfume.js (tried this example https://zizzamia.github.io/perfume/#/utilities/)

Any help would be greatly appreciated.

**Comment by Zizzamia** [comment]
@snipsy can you tell us more, how did you make it work in your case. It maybe helps @Artur-, and we could add this in the docs.

What kind of metrics are you looking for?
For Angular did you followed the docs?
http://zizzamia.github.io/perfume/#/angular/

**Comment by Zizzamia** [comment]
@Andarist any thoughts on this issue?

**Comment by Andarist** [comment]
I'm not sure how @Artur- wants to consume the library - if he doesn't use any bundling how `perfume.js` is even resolved to the actual file? Such import is node/bundlers specific & is not compatible with the browsers so I assume there must be some kind of bundling used.

**Comment by Zizzamia** [comment]
Closing this issue because it seems not a problem anymore.
