### ISSUE TITLE
Question - how to measure async code

### ISSUE THREAD

**Issue by petrbrzek** [Zizzamia/perfume.js#58]
Hi, first of all, thank you for a great library 👏. I'm wondering what's the best practice in term of measuring async code. Let's say you measure the time for some async API requests and you run those requests simultaneously and you want to use just one event name.

Example code:

```js
async function apiExample(url) {
  perfume.start('api-example')
  const response = await fetch(url)
  perfume.end('api-example')
  return response.json()
}

const first = apiExample('http://example.com/movies.json')
const second = apiExample('http://example.com/another.json')
```

Those two calls interfere with each other. What's the correct way of doing this?

**Comment by petrbrzek** [comment]
Thanks. I understand this approach is better, but the example is rather simplified. We want to measure some user action where you start measuring in a file A and stop measuring in a file B and you can also do those actions in parallel. Eg. in our app, you can open a design or more design simultaneously and we are interested in "opening design" time. So what I think we are going do is to use Perfume inside of our custom Perf service where you can scope measures by some unique id, so measurement will not interfere with each other.  Another approach would be to create a new instance of Perfume every time, but that seems odd to me.

> Out of curiosity, can you share more on where do you use Perfume? Company name, use cases, city your team lives?

No problem, the company is called [Avocode](https://avocode.com) - it's a hand-off tool for designers and developers. We are based in Prague, Czech Republic. We wanted to start doing RUM as we have a lot of users from eastern countries and we are really not sure how well the app runs for them.

**Comment by Zizzamia** [comment]
Amazing, if you want we can talk via google hangout next week 😄
Feel free to private DM me on https://twitter.com/Zizzamia

I will personally avoid creating a new instance for each metric but instead wrap an instance inside your custom Perf service. Do you guys use any framework in particular? I'm looking forward to documenting more different use cases.
