### ISSUE TITLE
Add support for First Input

### ISSUE THREAD

**Issue by kurtextrem** [Zizzamia/perfume.js#60]
I'm just leaving this here for now until it's shipped: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/LN92hkaKCzw/Y-ryVxu5AgAJ

**Comment by Zizzamia** [comment]
Sounds good! I also need to review all the latest news from [Perfomance.now() Conf](https://www.youtube.com/watch?v=XvZ7-Uh0R4Q)

**Comment by Zizzamia** [comment]
Ciao @kurtextrem, do you know more about the progress of this metric?

**Comment by kurtextrem** [comment]
It's blocked by https://bugs.chromium.org/p/chromium/issues/detail?id=914500 so I guess it won't happen rn.

**Comment by Zizzamia** [comment]
Cool Cool, gotcha! 
A few other ideas I'm keeping my eyes on are:
- Hero Text Timing, https://wicg.github.io/element-timing/ https://docs.google.com/document/d/1blFeMVdqxB0V3BAJh60ptOBFY7cJSXnf7VyW3wspbZ8/edit#heading=h.eny79fwwx642
- Expected Queueing Time, https://gist.github.com/paulirish/7fbadc9556c9dc97e9ceac6cf078a5cb

**Comment by kurtextrem** [comment]
Pretty interesting stuff!

**Comment by Zizzamia** [comment]
It's time to release Perfume v3 with **first-input** support and using the **buffered** flag.

https://chromium.googlesource.com/chromium/src/+/2f649e5932821fec499ec23bd95d5f5d24418b0a/third_party/blink/web_tests/external/wpt/event-timing/onloadthenobserve-firstInput.html

**Comment by Zizzamia** [comment]
Keep an eye on https://chromium-review.googlesource.com/c/chromium/src/+/1685975

**Comment by Zizzamia** [comment]
Added support with [v3.0.0-rc.1](https://github.com/Zizzamia/perfume.js/releases/tag/v3.0.0-rc.1)
