### ISSUE TITLE
FCP and FP don't log when doing server prerenders

### ISSUE THREAD

**Issue by NateWarner** [Zizzamia/perfume.js#61]
Worth mentioning since it wasn't brought up in the documentation is that if a site is doing prerenders, then FCP and FP do not fire. Once I emulate LTE or slower speeds, the prerender content gets in FCP before the Angular packages have finished downloading and, by extension, before PerfumeJS is in play. As a result, those two metrics never fire.

I would imagine this may also be the case for people who do shell content within their index.html as recommended by many Angular guides out there.

Not sure how you would easily resolve this without having a separate bundle that is HEAD DOM-blocking specifically for FCP and FP. May want to mention it in the documentation, though.

**Comment by Zizzamia** [comment]
Yup, you right! As explained here
https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics

> Important: you must ensure your PerformanceObserver is registered in the <head> of your document before any stylesheets, so it runs before FP/FCP happens.
> 
> This will no longer be necessary once Level 2 of the Performance Observer spec is implemented, as it introduces a buffered flag that allows you to access performance entries queued prior to the PerformanceObserver being created.

Do you wanna propose a PR to update the documentation? Otherwise, I will work on later on.
Thank you for sharing your experience and opening this question.

**Comment by jessetsilva** [comment]
Hi @Zizzamia , do you know of any workaround that can make it work while the new spec is not implemented?

Thank you.

**Comment by Zizzamia** [comment]
Ciao, and sorry for this late reply.
The buffered flag is finally available in Chrome 🤩

You can already test it with [Perfume.js v3.0.0-rc.5](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)

I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.
