### ISSUE TITLE
Add SSR support, init only on client

### ISSUE THREAD

**Issue by TUNER88** [Zizzamia/perfume.js#66]
Server side rendering ends up with following error:
```
ReferenceError: addEventListener is not defined
    at eval (webpack:///./node_modules/first-input-delay/src/first-input-delay.js?:179:4)
    at Object../node_modules/first-input-delay/src/first-input-delay.js (<anonymous>:12488:1)
    at __webpack_require__ (<anonymous>:20:30)
    at Module.eval (webpack:///./node_modules/perfume.js/dist/perfume.es5.min.js?:2:122)
```

Could you please provide some example configs how to get it running only on client side?

**Comment by Zizzamia** [comment]
Have you tried by checking the Production Environment? What SSR library do you use? I can try to create a mini demo for it.

**Comment by Zizzamia** [comment]
Ciao, and sorry for this late reply.
Also, we have the buffered flag enabled which will help for Server Side Rendering and Google Tag Manager issues. 🤩
With V3 we will drop the support for Paint Timing and First Input Delay polyfill and only serve the results from the Vanilla API 🍾

You can already test it with [Perfume.js v3.0.0-rc.5](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)

I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.
