### ISSUE TITLE
.js file?

### ISSUE THREAD

**Issue by DanielSokil** [Zizzamia/perfume.js#7]
Does this run on client-side? or node.js only?
Ex.
`<script src="node_modules/prefume.js/dist/prefume.js"></script>`

**Comment by Zizzamia** [comment]
Perfume is only **client-side** because of `window.performance` used to calculate the browser metrics.

I just updated the docs, have you tried using the [Universal Module Definition](https://github.com/Zizzamia/perfume.js#importing-library)
```javascript
import Perfume from 'node_modules/perfume.js/perfume.umd.js';
```

PS: The library it's still on working progress ;)

**Comment by DanielSokil** [comment]
I will give it a try, Thanks.
