### ISSUE TITLE
Passing in timingVar to perfume.log()

### ISSUE THREAD

**Issue by jesperryom** [Zizzamia/perfume.js#70]
Using this nifty library, I found the way `timingVar` is defined during instantiation to be a little counter-intuitive. In my mind, a [`user timing variable`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#timingVar) is used to label the event that is being measured and might differ for different calls to `perfume.log()`. 

How would you feel about a tiny PR to add a third parameter to `.log()` for explicitely passing in a new `timingVar` value?

**Comment by Zizzamia** [comment]
You make a great point! I would love to see a PR about it, thank you 😄

**Comment by Zizzamia** [comment]
Because it might be going to conflict with https://github.com/Zizzamia/perfume.js/pull/69, I need to first change 
```js
log(metricName: string, duration: number)
```
to 
```js
log({ metricName: string, duration: number, gaTimingVar: string, customProperties })
```

which will support more custom requirements and future PRs.

Sounds good?

**Comment by Zizzamia** [comment]
Ciao, and sorry for this late reply.
With V3 we made some changes on log, sendTiming and analyticsTracker to be more flexible for future PR  🤩

You can already test it with [Perfume.js v3.0.0-rc.10](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)

I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.

But please feel free to create a Pull Request with the original adjustment you were proposing.
