### ISSUE TITLE
Using Perfume in a Lazy Loaded Module

### ISSUE THREAD

**Issue by bcarson** [Zizzamia/perfume.js#73]
Hi @Zizzamia! 

Can I use perfume in an Angular app with lazy loaded modules?

I know I can use `PerfumeModule.forRoot(perfumeConfig)` in the root but I'm not sure how to configure it in lazy loaded modules. 

If I try `PerfumeModule.forChild` I get this error in VSCode: 
`Property 'forChild' does not exist on type 'typeof PerfumeModule'.`

If I use `PerfumeModule.forRoot` in both modules, I get this error in the console:
```js
TypeError: Cannot read property 'pushTask' of undefined
    at perfume.es5.min.js:1
    at first-input-delay.js:68
```

which seems to be coming from the function below. Can you help? 🙏
````js
/**
   * Reports the first input delay and event (if they're recorded and valid)
   * by running the array of callback functions.
   */
  function reportFirstInputDelayIfRecordedAndValid() {
    // In some cases the recorded delay is clearly wrong, e.g. it's negative
    // or it's larger than the time between now and when the page was loaded.
    // - https://github.com/GoogleChromeLabs/first-input-delay/issues/4
    // - https://github.com/GoogleChromeLabs/first-input-delay/issues/6
    // - https://github.com/GoogleChromeLabs/first-input-delay/issues/7
    if (firstInputDelay >= 0 &&
        firstInputDelay < firstInputTimeStamp - startTimeStamp) {
      callbacks.forEach(function(callback) {
        callback(firstInputDelay, firstInputEvent);
      });
      callbacks = [];
    }
  }

**Comment by Zizzamia** [comment]
Ciao, and sorry for this late reply.
Also, we have the buffered flag enabled which will help for Server Side Rendering and Google Tag Manager issues. 🤩
With V3 we will drop the support for Paint Timing and First Input Delay polyfill and only serve the results from the Vanilla API 🍾

You can already test it with [Perfume.js v3.0.0-rc.5](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)

I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.

Please let me know if V3 works better with your problem.

**Comment by Zizzamia** [comment]
Ciao @bcarson do you still have this problem with the latest Angular version, also @juristr any thoughts about this problem?

**Comment by Zizzamia** [comment]
Closing this for no progress over the last six months.
