### ISSUE TITLE
FID needs additonal inline snipplet from google lib

### ISSUE THREAD

**Issue by nilskuhn** [Zizzamia/perfume.js#76]
I am observing the following error if I am using perfume.js with FID activated in config but don't integrate googles [FID library](https://github.com/GoogleChromeLabs/first-input-delay/blob/master/dist/first-input-delay.min.js) in the page:
```
Uncaught (in promise) ReferenceError: perfMetrics is not defined
```
I think it's valid to not integrate the lib as a dependency because of the recommendation to inline it in the head of the page. 
But the fact that perfume will fail to measure fid and produces a runtime error if one doesn't integrate that snippet in the page should at least be mentioned in README, I think.

**Comment by Zizzamia** [comment]
Thank you for the feedback.
What DIST are you using? It should be included in the main Perfume bundle.
Can you share more on how are you using Perfume in your App.

**Comment by Zizzamia** [comment]
Ciao, and sorry for this late reply.
With V3 we will drop the support for Paint Timing and First Input Delay polyfill and only serve the results from the Vanilla API 🍾
Also, we have the buffered flag enabled which will help for Server Side Rendering and Google Tag Manager issues. 🤩

You can already test it with [Perfume.js v3.0.0-rc.5](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)

I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.
