### ISSUE TITLE
PerfumeModule Causes Production Build Error in Angular

### ISSUE THREAD

**Issue by theAndrewCline** [Zizzamia/perfume.js#86]
When running `ng build --prod` I get the following error

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'PerfumeModule' was called.

Removing PerfumeModule fixes the issue. but obviously I would like to tests my production build

**Comment by Zizzamia** [comment]
Would you mind share a little bit more with me please.
Angular version: ?
Perfume version: ?
Angular CLI version: ?

Can you share also the trace of the error please.

**Comment by theAndrewCline** [comment]
Sure thing! 

Angular version: 8.2.0
Perfume version: 3.0.0-rc.5
Angular CLI version: 8.2.0

**Comment by theAndrewCline** [comment]
Hey, that works! 👍 Thanks for your help!
