### ISSUE TITLE
 Illegal invocation

### ISSUE THREAD

**Issue by WarrenJones** [Zizzamia/perfume.js#87]
![image](https://user-images.githubusercontent.com/8704779/66645124-352c9400-ec55-11e9-806f-2f945365e6d4.png)
I've copy the source code and run it but every single time it shows like this

**Comment by WarrenJones** [comment]
![image](https://user-images.githubusercontent.com/8704779/66648971-880b4900-ec5f-11e9-89b0-5dc3e7052e25.png)
Here I annotated the requestIdleCallback then it works

**Comment by Zizzamia** [comment]
Thank you for opening this issue, can you please share more on:
- Perfume.js version you are using
- how are you using Perfume in your code
- what bundle are you using
- what browser version you see the error

Happy to help

**Comment by WarrenJones** [comment]
1.Perfume.js version is the lastest version I cloned from github
2.I just copy the code in a new folder and import Perfume.js on my webApp as in the example
3.I am using webpack for bundling
4.using Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Zizzamia** [comment]
The recommended way to use Perfume.js is by npm and download the stable version `2.1.2` or the experimental one `3.0.0-rc.10`, especially because I am working on the latest v3 which is still working in progress.

```
npm install perfume.js --save-dev
```

Any particular reason why you are not using `npm`?

**Comment by WarrenJones** [comment]
I just wanna use your smart code and base on it I need to recreate from it for my webview h5 page so that I can combine with the app information to make an better adjustment to satisfy my expectation.

**Comment by WarrenJones** [comment]
If it's possible I wanna join your project cause now our app got over 10,000,000 dau so that every h5 we got over 2,000,000 users every day all around the world,It will be a good testing for the project and I hope I can make some contributions!

**Comment by Zizzamia** [comment]
Have you built the code before using it?
`npm run build`

**Comment by Zizzamia** [comment]
But again, `master` at the moment is a working in progress. Just take the built code from **npm** and use it in your App.

**Comment by WarrenJones** [comment]
Ok,thank you so much
