### ISSUE TITLE
fix: pushTask is undefined during HotReloading

### ISSUE THREAD

**Issue by kmartinezmedia** [Zizzamia/perfume.js#88]
Hi, great library!
Can you please cover the case when during HotReloading throw this error
![image](https://user-images.githubusercontent.com/6308123/66963866-ae4b3300-f029-11e9-9480-b8e3d73f36ef.png)

**Comment by Zizzamia** [comment]
Fix in https://github.com/Zizzamia/perfume.js/commit/2668d3428d2fd76f3a588de03e3108a07706e33d
and 
https://github.com/Zizzamia/perfume.js/commit/cba672ca4a1346a3fdfcf0628cf064731a67c2b0
