### ISSUE TITLE
browserTracker option not used

### ISSUE THREAD

**Issue by chiefcll** [Zizzamia/perfume.js#92]
https://github.com/Zizzamia/perfume.js/blob/cc2cac06382a0a756441992b9f2d74aa997be59f/docs/src/app/perfume.config.ts#L37

Should be removed including readme files

**Comment by Zizzamia** [comment]
Ciao, thank you for the heads up!
I just published Perfume v4 and updated both the [website](https://zizzamia.github.io/perfume/) and the Readme.
In the next few weeks, I am going to have v4 under several stress tests before fully announce it 😄

Do you use Perfume at the moment in Comcast?
I am thinking to have a section in the README to have logos for companies that officially use Perfume.

**Comment by chiefcll** [comment]
Thanks for the library! I'm checking it out now. If we do use it I'll have to check with our open source committee if you could use our logo on your site.

**Comment by Zizzamia** [comment]
We use it in production at Coinbase at the moment, let me know if you have any questions on how to get the best out of the library.
