### ISSUE TITLE
Feature: Gather Fetch request metrics

### ISSUE THREAD

**Issue by chiefcll** [Zizzamia/perfume.js#93]
👋 

I'd like to do something like the following:
```
export function forFetchRequests() {
  // Check performance support
  if (performance === undefined) {
    return [];
  }

  // Get a list of "resource" performance entries
  let resources = performance.getEntriesByType('resource');
  if (resources === undefined || resources.length <= 0) {
    return [];
  }

  const fetches = [];
  for (let i = 0; i < resources.length; i++) {
    let resource = resources[i];
    if (
      (resource.initiatorType === 'xmlhttprequest' ||
        resource.initiatorType === 'fetch') &&
      shouldTrack(resource.name)
    ) {
      fetches.push(calcTiming(resource));
    }
  }
  return fetches;
}
```

Once the page is fully loaded - I'd like to get all the AJAX calls that we're made (with some kind of `shouldTrack` filter function to limit domain etc)

Let me know what you think. This would avoid the need to wrap the network requests we care about in a start / end.

**Comment by Zizzamia** [comment]
Tell me more, what are the goals? What metrics do you want to create, and what value over time do you want to compare?

It is really interesting and we can definitely play around with the PerformanceObserver and Resources collected.

I already have an experimental feature I am playing with it recently https://github.com/Zizzamia/perfume.js/blob/master/src/perfume.ts#L309

**Comment by chiefcll** [comment]
I'm working on capturing performance measurements for our sites. Our web apps are single page applications which make API calls for user specific information. Thus our full time to interactive is when JS is processed and API calls are completed. Each of our applications also mark when they consider themselves ready.

I don't know how much of this should be Perfume's responsibility, but interacting with the resource timing api might be something it should do.

**Comment by Zizzamia** [comment]
Sounds good, before making any change on Perfume we want to make sure to understand what metric is important to create.
We agreed that collect Resource Timing information is valuable, now the next steps are probably divided this data into two classes:
- what? we can collect information related to APIs, images, js files
- when? we should decide when we want to stop measuring, to have a time frame that is similar cross all users and to create a valuable metric to measure over time.

Right now if you enable `dataConsumption: true` we do a SUM of all resource timing values from the loading of the page till the First Input Delay.
What we can do is:
1) not only give a SUM of all data but also divide them between APIs, images and js to have a more granular information
2) we could decide to extend this metric to a longer period, which I don't know quite yet when is easier and reliable to do so.

This is just what is on top of my mind, does it makes sense?

**Comment by chiefcll** [comment]
what - part of the options would be a filter function. End user would write what they are interested in. (might be resourceType + filter function)
when - In the case of a single page app, you would not stop measuring. We'd send all the calls before exit of the app.

I like #1 for dataConsumption...

**Comment by Zizzamia** [comment]
Ok, it makes sense, the ability to leave the user freedom to customize what they want to filter out.
You say, send the calls before exiting the app, but what do you want to send? The sum of all Kb downloaded or anything in particular?

We need in some way normalized this data to make it very simple to monitoring over time cross million of users and hundreds of countries.

But we are getting closer to a practical propose, that's **exciting**. 🔥🔥🔥

**Comment by chiefcll** [comment]
We use sendBeacon - we'd send whatever API calls were made - the info we want is call size KB - and how long the API took to respond.

**Comment by Zizzamia** [comment]
Awesome, working on something you might like.

**Comment by Zizzamia** [comment]
Ciao @chiefcll, with the new version 4.3.0 now you have access to the Resource Timing.
https://zizzamia.github.io/perfume/#/resource-timing/

Feel free to play around it and looking forward to hear what you think about it.
