### ISSUE TITLE
Should be installed as a dependency and not a dev-dependency

### ISSUE THREAD

**Issue by aroramayur** [Zizzamia/perfume.js#98]
I see in the instructions that this should be installed as a dev-dependency ( --save-dev ). Shouldn't this be installed as a dependency?

**Comment by Zizzamia** [comment]
Ops, you right!
Thank you for noticing this, would you mind opening a PR with the fix.
🙌

**Comment by aroramayur** [comment]
Done. 
https://github.com/Zizzamia/perfume.js/pull/100
